language: php

php:
  - 7.1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `travis-ci`;'

before_deploy:
  - composer global require "laravel/envoy=~1.0";
  - openssl aes-256-cbc -K $encrypted_97588c8af04b_key -iv $encrypted_97588c8af04b_iv -in storage/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - if [ $(! echo "$PATH" | grep -q "$HOME/.composer/vendor/bin") ]; then export PATH=$PATH:$HOME/.composer/vendor/bin; fi;
  - echo $PATH;
  - cd $TRAVIS_BUILD_DIR && envoy run deploy;

deploy:
  - provider: script
    skip_cleanup: true
    script: storage/deploy.sh
    on:
      branch: master

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --force --no-interaction

script: vendor/bin/phpunit

services:
  - mysql
